/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkbenchRouteImport } from './routes/workbench'
import { Route as UsersRouteImport } from './routes/users'
import { Route as SystemConfigRouteImport } from './routes/system-config'
import { Route as RolesRouteImport } from './routes/roles'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ReconWorkflowsRouteImport } from './routes/recon-workflows'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PipelinesRouteImport } from './routes/pipelines'
import { Route as OverviewRouteImport } from './routes/overview'
import { Route as MonitoringRouteImport } from './routes/monitoring'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DownloadsRouteImport } from './routes/downloads'
import { Route as DatabaseConnectionsRouteImport } from './routes/database-connections'
import { Route as DataSourcesRouteImport } from './routes/data-sources'
import { Route as CasesRouteImport } from './routes/cases'
import { Route as AuditLogsRouteImport } from './routes/audit-logs'
import { Route as AccessDeniedRouteImport } from './routes/access-denied'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RatingIndexRouteImport } from './routes/rating/index'
import { Route as RatingSnapshotsRouteImport } from './routes/rating/snapshots'
import { Route as RatingSimulationRouteImport } from './routes/rating/simulation'
import { Route as RatingRunsRouteImport } from './routes/rating/runs'
import { Route as RatingReportsRouteImport } from './routes/rating/reports'
import { Route as RatingRecordsRouteImport } from './routes/rating/records'
import { Route as RatingReconciliationRouteImport } from './routes/rating/reconciliation'
import { Route as RatingPipelineRouteImport } from './routes/rating/pipeline'
import { Route as RatingMonitoringRouteImport } from './routes/rating/monitoring'
import { Route as RatingLeakageRouteImport } from './routes/rating/leakage'
import { Route as RatingExceptionsRouteImport } from './routes/rating/exceptions'
import { Route as RatingConnectorsRouteImport } from './routes/rating/connectors'
import { Route as RatingCatalogRouteImport } from './routes/rating/catalog'
import { Route as RatingBalancesRouteImport } from './routes/rating/balances'
import { Route as RatingApprovalsRouteImport } from './routes/rating/approvals'
import { Route as AssuranceAppIdRouteImport } from './routes/assurance.$appId'
import { Route as RatingRulesIndexRouteImport } from './routes/rating/rules/index'
import { Route as AssuranceAppIdIndexRouteImport } from './routes/assurance.$appId.index'
import { Route as RatingRunsRunIdRouteImport } from './routes/rating/runs_.$runId'
import { Route as RatingRulesOverviewRouteImport } from './routes/rating/rules/overview'
import { Route as RatingRulesNewRouteImport } from './routes/rating/rules/new'
import { Route as RatingRulesImportRouteImport } from './routes/rating/rules/import'
import { Route as RatingRulesRuleIdRouteImport } from './routes/rating/rules/$ruleId'
import { Route as RatingExceptionsExceptionIdRouteImport } from './routes/rating/exceptions_.$exceptionId'
import { Route as RatingCdrsResultIdRouteImport } from './routes/rating/cdrs.$resultId'
import { Route as AssuranceAppIdSectionRouteImport } from './routes/assurance.$appId.$section'

const WorkbenchRoute = WorkbenchRouteImport.update({
  id: '/workbench',
  path: '/workbench',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemConfigRoute = SystemConfigRouteImport.update({
  id: '/system-config',
  path: '/system-config',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesRoute = RolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ReconWorkflowsRoute = ReconWorkflowsRouteImport.update({
  id: '/recon-workflows',
  path: '/recon-workflows',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelinesRoute = PipelinesRouteImport.update({
  id: '/pipelines',
  path: '/pipelines',
  getParentRoute: () => rootRouteImport,
} as any)
const OverviewRoute = OverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitoringRoute = MonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadsRoute = DownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const DatabaseConnectionsRoute = DatabaseConnectionsRouteImport.update({
  id: '/database-connections',
  path: '/database-connections',
  getParentRoute: () => rootRouteImport,
} as any)
const DataSourcesRoute = DataSourcesRouteImport.update({
  id: '/data-sources',
  path: '/data-sources',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesRoute = CasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditLogsRoute = AuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessDeniedRoute = AccessDeniedRouteImport.update({
  id: '/access-denied',
  path: '/access-denied',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RatingIndexRoute = RatingIndexRouteImport.update({
  id: '/rating/',
  path: '/rating/',
  getParentRoute: () => rootRouteImport,
} as any)
const RatingSnapshotsRoute = RatingSnapshotsRouteImport.update({
  id: '/rating/snapshots',
  path: '/rating/snapshots',
  getParentRoute: () => rootRouteImport,
} as any)
const RatingSimulationRoute = RatingSimulationRouteImport.update({
  id: '/rating/simulation',
  path: '/rating/simulation',
  getParentRoute: () => rootRouteImport,
} as any)
const RatingRunsRoute = RatingRunsRouteImport.update({
  id: '/rating/runs',
  path: '/rating/runs',
  getParentRoute: () => rootRouteImport,
} as any)
const RatingReportsRoute = RatingReportsRouteImport.update({
  id: '/rating/reports',
  path: '/rating/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RatingRecordsRoute = RatingRecordsRouteImport.update({
  id: '/rating/records',
  path: '/rating/records',
  getParentRoute: () => rootRouteImport,
} as any)
const RatingReconciliationRoute = RatingReconciliationRouteImport.update({
  id: '/rating/reconciliation',
  path: '/rating/reconciliation',
  getParentRoute: () => rootRouteImport,
} as any)
const RatingPipelineRoute = RatingPipelineRouteImport.update({
  id: '/rating/pipeline',
  path: '/rating/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const RatingMonitoringRoute = RatingMonitoringRouteImport.update({
  id: '/rating/monitoring',
  path: '/rating/monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const RatingLeakageRoute = RatingLeakageRouteImport.update({
  id: '/rating/leakage',
  path: '/rating/leakage',
  getParentRoute: () => rootRouteImport,
} as any)
const RatingExceptionsRoute = RatingExceptionsRouteImport.update({
  id: '/rating/exceptions',
  path: '/rating/exceptions',
  getParentRoute: () => rootRouteImport,
} as any)
const RatingConnectorsRoute = RatingConnectorsRouteImport.update({
  id: '/rating/connectors',
  path: '/rating/connectors',
  getParentRoute: () => rootRouteImport,
} as any)
const RatingCatalogRoute = RatingCatalogRouteImport.update({
  id: '/rating/catalog',
  path: '/rating/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const RatingBalancesRoute = RatingBalancesRouteImport.update({
  id: '/rating/balances',
  path: '/rating/balances',
  getParentRoute: () => rootRouteImport,
} as any)
const RatingApprovalsRoute = RatingApprovalsRouteImport.update({
  id: '/rating/approvals',
  path: '/rating/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const AssuranceAppIdRoute = AssuranceAppIdRouteImport.update({
  id: '/assurance/$appId',
  path: '/assurance/$appId',
  getParentRoute: () => rootRouteImport,
} as any)
const RatingRulesIndexRoute = RatingRulesIndexRouteImport.update({
  id: '/rating/rules/',
  path: '/rating/rules/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssuranceAppIdIndexRoute = AssuranceAppIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AssuranceAppIdRoute,
} as any)
const RatingRunsRunIdRoute = RatingRunsRunIdRouteImport.update({
  id: '/rating/runs_/$runId',
  path: '/rating/runs/$runId',
  getParentRoute: () => rootRouteImport,
} as any)
const RatingRulesOverviewRoute = RatingRulesOverviewRouteImport.update({
  id: '/rating/rules/overview',
  path: '/rating/rules/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const RatingRulesNewRoute = RatingRulesNewRouteImport.update({
  id: '/rating/rules/new',
  path: '/rating/rules/new',
  getParentRoute: () => rootRouteImport,
} as any)
const RatingRulesImportRoute = RatingRulesImportRouteImport.update({
  id: '/rating/rules/import',
  path: '/rating/rules/import',
  getParentRoute: () => rootRouteImport,
} as any)
const RatingRulesRuleIdRoute = RatingRulesRuleIdRouteImport.update({
  id: '/rating/rules/$ruleId',
  path: '/rating/rules/$ruleId',
  getParentRoute: () => rootRouteImport,
} as any)
const RatingExceptionsExceptionIdRoute =
  RatingExceptionsExceptionIdRouteImport.update({
    id: '/rating/exceptions_/$exceptionId',
    path: '/rating/exceptions/$exceptionId',
    getParentRoute: () => rootRouteImport,
  } as any)
const RatingCdrsResultIdRoute = RatingCdrsResultIdRouteImport.update({
  id: '/rating/cdrs/$resultId',
  path: '/rating/cdrs/$resultId',
  getParentRoute: () => rootRouteImport,
} as any)
const AssuranceAppIdSectionRoute = AssuranceAppIdSectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => AssuranceAppIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access-denied': typeof AccessDeniedRoute
  '/audit-logs': typeof AuditLogsRoute
  '/cases': typeof CasesRoute
  '/data-sources': typeof DataSourcesRoute
  '/database-connections': typeof DatabaseConnectionsRoute
  '/downloads': typeof DownloadsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/monitoring': typeof MonitoringRoute
  '/overview': typeof OverviewRoute
  '/pipelines': typeof PipelinesRoute
  '/profile': typeof ProfileRoute
  '/recon-workflows': typeof ReconWorkflowsRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/roles': typeof RolesRoute
  '/system-config': typeof SystemConfigRoute
  '/users': typeof UsersRoute
  '/workbench': typeof WorkbenchRoute
  '/assurance/$appId': typeof AssuranceAppIdRouteWithChildren
  '/rating/approvals': typeof RatingApprovalsRoute
  '/rating/balances': typeof RatingBalancesRoute
  '/rating/catalog': typeof RatingCatalogRoute
  '/rating/connectors': typeof RatingConnectorsRoute
  '/rating/exceptions': typeof RatingExceptionsRoute
  '/rating/leakage': typeof RatingLeakageRoute
  '/rating/monitoring': typeof RatingMonitoringRoute
  '/rating/pipeline': typeof RatingPipelineRoute
  '/rating/reconciliation': typeof RatingReconciliationRoute
  '/rating/records': typeof RatingRecordsRoute
  '/rating/reports': typeof RatingReportsRoute
  '/rating/runs': typeof RatingRunsRoute
  '/rating/simulation': typeof RatingSimulationRoute
  '/rating/snapshots': typeof RatingSnapshotsRoute
  '/rating/': typeof RatingIndexRoute
  '/assurance/$appId/$section': typeof AssuranceAppIdSectionRoute
  '/rating/cdrs/$resultId': typeof RatingCdrsResultIdRoute
  '/rating/exceptions/$exceptionId': typeof RatingExceptionsExceptionIdRoute
  '/rating/rules/$ruleId': typeof RatingRulesRuleIdRoute
  '/rating/rules/import': typeof RatingRulesImportRoute
  '/rating/rules/new': typeof RatingRulesNewRoute
  '/rating/rules/overview': typeof RatingRulesOverviewRoute
  '/rating/runs/$runId': typeof RatingRunsRunIdRoute
  '/assurance/$appId/': typeof AssuranceAppIdIndexRoute
  '/rating/rules/': typeof RatingRulesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access-denied': typeof AccessDeniedRoute
  '/audit-logs': typeof AuditLogsRoute
  '/cases': typeof CasesRoute
  '/data-sources': typeof DataSourcesRoute
  '/database-connections': typeof DatabaseConnectionsRoute
  '/downloads': typeof DownloadsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/monitoring': typeof MonitoringRoute
  '/overview': typeof OverviewRoute
  '/pipelines': typeof PipelinesRoute
  '/profile': typeof ProfileRoute
  '/recon-workflows': typeof ReconWorkflowsRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/roles': typeof RolesRoute
  '/system-config': typeof SystemConfigRoute
  '/users': typeof UsersRoute
  '/workbench': typeof WorkbenchRoute
  '/rating/approvals': typeof RatingApprovalsRoute
  '/rating/balances': typeof RatingBalancesRoute
  '/rating/catalog': typeof RatingCatalogRoute
  '/rating/connectors': typeof RatingConnectorsRoute
  '/rating/exceptions': typeof RatingExceptionsRoute
  '/rating/leakage': typeof RatingLeakageRoute
  '/rating/monitoring': typeof RatingMonitoringRoute
  '/rating/pipeline': typeof RatingPipelineRoute
  '/rating/reconciliation': typeof RatingReconciliationRoute
  '/rating/records': typeof RatingRecordsRoute
  '/rating/reports': typeof RatingReportsRoute
  '/rating/runs': typeof RatingRunsRoute
  '/rating/simulation': typeof RatingSimulationRoute
  '/rating/snapshots': typeof RatingSnapshotsRoute
  '/rating': typeof RatingIndexRoute
  '/assurance/$appId/$section': typeof AssuranceAppIdSectionRoute
  '/rating/cdrs/$resultId': typeof RatingCdrsResultIdRoute
  '/rating/exceptions/$exceptionId': typeof RatingExceptionsExceptionIdRoute
  '/rating/rules/$ruleId': typeof RatingRulesRuleIdRoute
  '/rating/rules/import': typeof RatingRulesImportRoute
  '/rating/rules/new': typeof RatingRulesNewRoute
  '/rating/rules/overview': typeof RatingRulesOverviewRoute
  '/rating/runs/$runId': typeof RatingRunsRunIdRoute
  '/assurance/$appId': typeof AssuranceAppIdIndexRoute
  '/rating/rules': typeof RatingRulesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/access-denied': typeof AccessDeniedRoute
  '/audit-logs': typeof AuditLogsRoute
  '/cases': typeof CasesRoute
  '/data-sources': typeof DataSourcesRoute
  '/database-connections': typeof DatabaseConnectionsRoute
  '/downloads': typeof DownloadsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/monitoring': typeof MonitoringRoute
  '/overview': typeof OverviewRoute
  '/pipelines': typeof PipelinesRoute
  '/profile': typeof ProfileRoute
  '/recon-workflows': typeof ReconWorkflowsRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/roles': typeof RolesRoute
  '/system-config': typeof SystemConfigRoute
  '/users': typeof UsersRoute
  '/workbench': typeof WorkbenchRoute
  '/assurance/$appId': typeof AssuranceAppIdRouteWithChildren
  '/rating/approvals': typeof RatingApprovalsRoute
  '/rating/balances': typeof RatingBalancesRoute
  '/rating/catalog': typeof RatingCatalogRoute
  '/rating/connectors': typeof RatingConnectorsRoute
  '/rating/exceptions': typeof RatingExceptionsRoute
  '/rating/leakage': typeof RatingLeakageRoute
  '/rating/monitoring': typeof RatingMonitoringRoute
  '/rating/pipeline': typeof RatingPipelineRoute
  '/rating/reconciliation': typeof RatingReconciliationRoute
  '/rating/records': typeof RatingRecordsRoute
  '/rating/reports': typeof RatingReportsRoute
  '/rating/runs': typeof RatingRunsRoute
  '/rating/simulation': typeof RatingSimulationRoute
  '/rating/snapshots': typeof RatingSnapshotsRoute
  '/rating/': typeof RatingIndexRoute
  '/assurance/$appId/$section': typeof AssuranceAppIdSectionRoute
  '/rating/cdrs/$resultId': typeof RatingCdrsResultIdRoute
  '/rating/exceptions_/$exceptionId': typeof RatingExceptionsExceptionIdRoute
  '/rating/rules/$ruleId': typeof RatingRulesRuleIdRoute
  '/rating/rules/import': typeof RatingRulesImportRoute
  '/rating/rules/new': typeof RatingRulesNewRoute
  '/rating/rules/overview': typeof RatingRulesOverviewRoute
  '/rating/runs_/$runId': typeof RatingRunsRunIdRoute
  '/assurance/$appId/': typeof AssuranceAppIdIndexRoute
  '/rating/rules/': typeof RatingRulesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access-denied'
    | '/audit-logs'
    | '/cases'
    | '/data-sources'
    | '/database-connections'
    | '/downloads'
    | '/forgot-password'
    | '/login'
    | '/monitoring'
    | '/overview'
    | '/pipelines'
    | '/profile'
    | '/recon-workflows'
    | '/reports'
    | '/reset-password'
    | '/roles'
    | '/system-config'
    | '/users'
    | '/workbench'
    | '/assurance/$appId'
    | '/rating/approvals'
    | '/rating/balances'
    | '/rating/catalog'
    | '/rating/connectors'
    | '/rating/exceptions'
    | '/rating/leakage'
    | '/rating/monitoring'
    | '/rating/pipeline'
    | '/rating/reconciliation'
    | '/rating/records'
    | '/rating/reports'
    | '/rating/runs'
    | '/rating/simulation'
    | '/rating/snapshots'
    | '/rating/'
    | '/assurance/$appId/$section'
    | '/rating/cdrs/$resultId'
    | '/rating/exceptions/$exceptionId'
    | '/rating/rules/$ruleId'
    | '/rating/rules/import'
    | '/rating/rules/new'
    | '/rating/rules/overview'
    | '/rating/runs/$runId'
    | '/assurance/$appId/'
    | '/rating/rules/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access-denied'
    | '/audit-logs'
    | '/cases'
    | '/data-sources'
    | '/database-connections'
    | '/downloads'
    | '/forgot-password'
    | '/login'
    | '/monitoring'
    | '/overview'
    | '/pipelines'
    | '/profile'
    | '/recon-workflows'
    | '/reports'
    | '/reset-password'
    | '/roles'
    | '/system-config'
    | '/users'
    | '/workbench'
    | '/rating/approvals'
    | '/rating/balances'
    | '/rating/catalog'
    | '/rating/connectors'
    | '/rating/exceptions'
    | '/rating/leakage'
    | '/rating/monitoring'
    | '/rating/pipeline'
    | '/rating/reconciliation'
    | '/rating/records'
    | '/rating/reports'
    | '/rating/runs'
    | '/rating/simulation'
    | '/rating/snapshots'
    | '/rating'
    | '/assurance/$appId/$section'
    | '/rating/cdrs/$resultId'
    | '/rating/exceptions/$exceptionId'
    | '/rating/rules/$ruleId'
    | '/rating/rules/import'
    | '/rating/rules/new'
    | '/rating/rules/overview'
    | '/rating/runs/$runId'
    | '/assurance/$appId'
    | '/rating/rules'
  id:
    | '__root__'
    | '/'
    | '/access-denied'
    | '/audit-logs'
    | '/cases'
    | '/data-sources'
    | '/database-connections'
    | '/downloads'
    | '/forgot-password'
    | '/login'
    | '/monitoring'
    | '/overview'
    | '/pipelines'
    | '/profile'
    | '/recon-workflows'
    | '/reports'
    | '/reset-password'
    | '/roles'
    | '/system-config'
    | '/users'
    | '/workbench'
    | '/assurance/$appId'
    | '/rating/approvals'
    | '/rating/balances'
    | '/rating/catalog'
    | '/rating/connectors'
    | '/rating/exceptions'
    | '/rating/leakage'
    | '/rating/monitoring'
    | '/rating/pipeline'
    | '/rating/reconciliation'
    | '/rating/records'
    | '/rating/reports'
    | '/rating/runs'
    | '/rating/simulation'
    | '/rating/snapshots'
    | '/rating/'
    | '/assurance/$appId/$section'
    | '/rating/cdrs/$resultId'
    | '/rating/exceptions_/$exceptionId'
    | '/rating/rules/$ruleId'
    | '/rating/rules/import'
    | '/rating/rules/new'
    | '/rating/rules/overview'
    | '/rating/runs_/$runId'
    | '/assurance/$appId/'
    | '/rating/rules/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessDeniedRoute: typeof AccessDeniedRoute
  AuditLogsRoute: typeof AuditLogsRoute
  CasesRoute: typeof CasesRoute
  DataSourcesRoute: typeof DataSourcesRoute
  DatabaseConnectionsRoute: typeof DatabaseConnectionsRoute
  DownloadsRoute: typeof DownloadsRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  MonitoringRoute: typeof MonitoringRoute
  OverviewRoute: typeof OverviewRoute
  PipelinesRoute: typeof PipelinesRoute
  ProfileRoute: typeof ProfileRoute
  ReconWorkflowsRoute: typeof ReconWorkflowsRoute
  ReportsRoute: typeof ReportsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RolesRoute: typeof RolesRoute
  SystemConfigRoute: typeof SystemConfigRoute
  UsersRoute: typeof UsersRoute
  WorkbenchRoute: typeof WorkbenchRoute
  AssuranceAppIdRoute: typeof AssuranceAppIdRouteWithChildren
  RatingApprovalsRoute: typeof RatingApprovalsRoute
  RatingBalancesRoute: typeof RatingBalancesRoute
  RatingCatalogRoute: typeof RatingCatalogRoute
  RatingConnectorsRoute: typeof RatingConnectorsRoute
  RatingExceptionsRoute: typeof RatingExceptionsRoute
  RatingLeakageRoute: typeof RatingLeakageRoute
  RatingMonitoringRoute: typeof RatingMonitoringRoute
  RatingPipelineRoute: typeof RatingPipelineRoute
  RatingReconciliationRoute: typeof RatingReconciliationRoute
  RatingRecordsRoute: typeof RatingRecordsRoute
  RatingReportsRoute: typeof RatingReportsRoute
  RatingRunsRoute: typeof RatingRunsRoute
  RatingSimulationRoute: typeof RatingSimulationRoute
  RatingSnapshotsRoute: typeof RatingSnapshotsRoute
  RatingIndexRoute: typeof RatingIndexRoute
  RatingCdrsResultIdRoute: typeof RatingCdrsResultIdRoute
  RatingExceptionsExceptionIdRoute: typeof RatingExceptionsExceptionIdRoute
  RatingRulesRuleIdRoute: typeof RatingRulesRuleIdRoute
  RatingRulesImportRoute: typeof RatingRulesImportRoute
  RatingRulesNewRoute: typeof RatingRulesNewRoute
  RatingRulesOverviewRoute: typeof RatingRulesOverviewRoute
  RatingRunsRunIdRoute: typeof RatingRunsRunIdRoute
  RatingRulesIndexRoute: typeof RatingRulesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workbench': {
      id: '/workbench'
      path: '/workbench'
      fullPath: '/workbench'
      preLoaderRoute: typeof WorkbenchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system-config': {
      id: '/system-config'
      path: '/system-config'
      fullPath: '/system-config'
      preLoaderRoute: typeof SystemConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles': {
      id: '/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof RolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recon-workflows': {
      id: '/recon-workflows'
      path: '/recon-workflows'
      fullPath: '/recon-workflows'
      preLoaderRoute: typeof ReconWorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipelines': {
      id: '/pipelines'
      path: '/pipelines'
      fullPath: '/pipelines'
      preLoaderRoute: typeof PipelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overview': {
      id: '/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof OverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitoring': {
      id: '/monitoring'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof MonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloads': {
      id: '/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof DownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/database-connections': {
      id: '/database-connections'
      path: '/database-connections'
      fullPath: '/database-connections'
      preLoaderRoute: typeof DatabaseConnectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-sources': {
      id: '/data-sources'
      path: '/data-sources'
      fullPath: '/data-sources'
      preLoaderRoute: typeof DataSourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases': {
      id: '/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof CasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-logs': {
      id: '/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AuditLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access-denied': {
      id: '/access-denied'
      path: '/access-denied'
      fullPath: '/access-denied'
      preLoaderRoute: typeof AccessDeniedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rating/': {
      id: '/rating/'
      path: '/rating'
      fullPath: '/rating/'
      preLoaderRoute: typeof RatingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rating/snapshots': {
      id: '/rating/snapshots'
      path: '/rating/snapshots'
      fullPath: '/rating/snapshots'
      preLoaderRoute: typeof RatingSnapshotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rating/simulation': {
      id: '/rating/simulation'
      path: '/rating/simulation'
      fullPath: '/rating/simulation'
      preLoaderRoute: typeof RatingSimulationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rating/runs': {
      id: '/rating/runs'
      path: '/rating/runs'
      fullPath: '/rating/runs'
      preLoaderRoute: typeof RatingRunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rating/reports': {
      id: '/rating/reports'
      path: '/rating/reports'
      fullPath: '/rating/reports'
      preLoaderRoute: typeof RatingReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rating/records': {
      id: '/rating/records'
      path: '/rating/records'
      fullPath: '/rating/records'
      preLoaderRoute: typeof RatingRecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rating/reconciliation': {
      id: '/rating/reconciliation'
      path: '/rating/reconciliation'
      fullPath: '/rating/reconciliation'
      preLoaderRoute: typeof RatingReconciliationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rating/pipeline': {
      id: '/rating/pipeline'
      path: '/rating/pipeline'
      fullPath: '/rating/pipeline'
      preLoaderRoute: typeof RatingPipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rating/monitoring': {
      id: '/rating/monitoring'
      path: '/rating/monitoring'
      fullPath: '/rating/monitoring'
      preLoaderRoute: typeof RatingMonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rating/leakage': {
      id: '/rating/leakage'
      path: '/rating/leakage'
      fullPath: '/rating/leakage'
      preLoaderRoute: typeof RatingLeakageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rating/exceptions': {
      id: '/rating/exceptions'
      path: '/rating/exceptions'
      fullPath: '/rating/exceptions'
      preLoaderRoute: typeof RatingExceptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rating/connectors': {
      id: '/rating/connectors'
      path: '/rating/connectors'
      fullPath: '/rating/connectors'
      preLoaderRoute: typeof RatingConnectorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rating/catalog': {
      id: '/rating/catalog'
      path: '/rating/catalog'
      fullPath: '/rating/catalog'
      preLoaderRoute: typeof RatingCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rating/balances': {
      id: '/rating/balances'
      path: '/rating/balances'
      fullPath: '/rating/balances'
      preLoaderRoute: typeof RatingBalancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rating/approvals': {
      id: '/rating/approvals'
      path: '/rating/approvals'
      fullPath: '/rating/approvals'
      preLoaderRoute: typeof RatingApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assurance/$appId': {
      id: '/assurance/$appId'
      path: '/assurance/$appId'
      fullPath: '/assurance/$appId'
      preLoaderRoute: typeof AssuranceAppIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rating/rules/': {
      id: '/rating/rules/'
      path: '/rating/rules'
      fullPath: '/rating/rules/'
      preLoaderRoute: typeof RatingRulesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assurance/$appId/': {
      id: '/assurance/$appId/'
      path: '/'
      fullPath: '/assurance/$appId/'
      preLoaderRoute: typeof AssuranceAppIdIndexRouteImport
      parentRoute: typeof AssuranceAppIdRoute
    }
    '/rating/runs_/$runId': {
      id: '/rating/runs_/$runId'
      path: '/rating/runs/$runId'
      fullPath: '/rating/runs/$runId'
      preLoaderRoute: typeof RatingRunsRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rating/rules/overview': {
      id: '/rating/rules/overview'
      path: '/rating/rules/overview'
      fullPath: '/rating/rules/overview'
      preLoaderRoute: typeof RatingRulesOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rating/rules/new': {
      id: '/rating/rules/new'
      path: '/rating/rules/new'
      fullPath: '/rating/rules/new'
      preLoaderRoute: typeof RatingRulesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rating/rules/import': {
      id: '/rating/rules/import'
      path: '/rating/rules/import'
      fullPath: '/rating/rules/import'
      preLoaderRoute: typeof RatingRulesImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rating/rules/$ruleId': {
      id: '/rating/rules/$ruleId'
      path: '/rating/rules/$ruleId'
      fullPath: '/rating/rules/$ruleId'
      preLoaderRoute: typeof RatingRulesRuleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rating/exceptions_/$exceptionId': {
      id: '/rating/exceptions_/$exceptionId'
      path: '/rating/exceptions/$exceptionId'
      fullPath: '/rating/exceptions/$exceptionId'
      preLoaderRoute: typeof RatingExceptionsExceptionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rating/cdrs/$resultId': {
      id: '/rating/cdrs/$resultId'
      path: '/rating/cdrs/$resultId'
      fullPath: '/rating/cdrs/$resultId'
      preLoaderRoute: typeof RatingCdrsResultIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assurance/$appId/$section': {
      id: '/assurance/$appId/$section'
      path: '/$section'
      fullPath: '/assurance/$appId/$section'
      preLoaderRoute: typeof AssuranceAppIdSectionRouteImport
      parentRoute: typeof AssuranceAppIdRoute
    }
  }
}

interface AssuranceAppIdRouteChildren {
  AssuranceAppIdSectionRoute: typeof AssuranceAppIdSectionRoute
  AssuranceAppIdIndexRoute: typeof AssuranceAppIdIndexRoute
}

const AssuranceAppIdRouteChildren: AssuranceAppIdRouteChildren = {
  AssuranceAppIdSectionRoute: AssuranceAppIdSectionRoute,
  AssuranceAppIdIndexRoute: AssuranceAppIdIndexRoute,
}

const AssuranceAppIdRouteWithChildren = AssuranceAppIdRoute._addFileChildren(
  AssuranceAppIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessDeniedRoute: AccessDeniedRoute,
  AuditLogsRoute: AuditLogsRoute,
  CasesRoute: CasesRoute,
  DataSourcesRoute: DataSourcesRoute,
  DatabaseConnectionsRoute: DatabaseConnectionsRoute,
  DownloadsRoute: DownloadsRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  MonitoringRoute: MonitoringRoute,
  OverviewRoute: OverviewRoute,
  PipelinesRoute: PipelinesRoute,
  ProfileRoute: ProfileRoute,
  ReconWorkflowsRoute: ReconWorkflowsRoute,
  ReportsRoute: ReportsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RolesRoute: RolesRoute,
  SystemConfigRoute: SystemConfigRoute,
  UsersRoute: UsersRoute,
  WorkbenchRoute: WorkbenchRoute,
  AssuranceAppIdRoute: AssuranceAppIdRouteWithChildren,
  RatingApprovalsRoute: RatingApprovalsRoute,
  RatingBalancesRoute: RatingBalancesRoute,
  RatingCatalogRoute: RatingCatalogRoute,
  RatingConnectorsRoute: RatingConnectorsRoute,
  RatingExceptionsRoute: RatingExceptionsRoute,
  RatingLeakageRoute: RatingLeakageRoute,
  RatingMonitoringRoute: RatingMonitoringRoute,
  RatingPipelineRoute: RatingPipelineRoute,
  RatingReconciliationRoute: RatingReconciliationRoute,
  RatingRecordsRoute: RatingRecordsRoute,
  RatingReportsRoute: RatingReportsRoute,
  RatingRunsRoute: RatingRunsRoute,
  RatingSimulationRoute: RatingSimulationRoute,
  RatingSnapshotsRoute: RatingSnapshotsRoute,
  RatingIndexRoute: RatingIndexRoute,
  RatingCdrsResultIdRoute: RatingCdrsResultIdRoute,
  RatingExceptionsExceptionIdRoute: RatingExceptionsExceptionIdRoute,
  RatingRulesRuleIdRoute: RatingRulesRuleIdRoute,
  RatingRulesImportRoute: RatingRulesImportRoute,
  RatingRulesNewRoute: RatingRulesNewRoute,
  RatingRulesOverviewRoute: RatingRulesOverviewRoute,
  RatingRunsRunIdRoute: RatingRunsRunIdRoute,
  RatingRulesIndexRoute: RatingRulesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
