"""rating assurance: msc source, subscriber groups, per-usage audit

Revision ID: 0013
Revises: 0012
Create Date: 2026-07-30 17:59:06.830892

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0013'
down_revision: str | None = '0012'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calculation_component',
    sa.Column('component_id', sa.String(length=36), nullable=False),
    sa.Column('usage_id', sa.String(length=128), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=True),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('component_type', sa.String(length=32), nullable=False),
    sa.Column('rule_id', sa.String(length=36), nullable=True),
    sa.Column('rule_key', sa.String(length=80), nullable=True),
    sa.Column('input_quantity', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('input_amount', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('adjustment_amount', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('output_amount', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('calculation_detail', sa.Text(), server_default='', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('component_id', name=op.f('pk_calculation_component')),
    sa.UniqueConstraint('usage_id', 'sequence_number', name='uq_calculation_component_usage_id')
    )
    op.create_index('ix_calculation_component_run', 'calculation_component', ['run_id'], unique=False)
    op.create_index('ix_calculation_component_type', 'calculation_component', ['component_type'], unique=False)
    op.create_index('ix_calculation_component_usage', 'calculation_component', ['usage_id'], unique=False)
    op.create_table('holiday_calendar',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('country_code', sa.String(length=8), server_default='KH', nullable=False),
    sa.Column('holiday_date', sa.Date(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('day_type', sa.String(length=16), server_default='HOLIDAY', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_holiday_calendar')),
    sa.UniqueConstraint('country_code', 'holiday_date', name='uq_holiday_calendar_country_code')
    )
    op.create_index('ix_holiday_calendar_date', 'holiday_calendar', ['holiday_date'], unique=False)
    op.create_table('msc_ingest_cursor',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_system', sa.String(length=64), nullable=False),
    sa.Column('source_table', sa.String(length=128), nullable=False),
    sa.Column('last_source_id', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('last_pulled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('records_pulled', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_msc_ingest_cursor')),
    sa.UniqueConstraint('source_system', 'source_table', name='uq_msc_ingest_cursor_source_system')
    )
    op.create_table('rating_result_final',
    sa.Column('rating_result_id', sa.String(length=36), nullable=False),
    sa.Column('usage_id', sa.String(length=128), nullable=False),
    sa.Column('charge_component', sa.String(length=32), server_default='TOTAL', nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=True),
    sa.Column('cdr_enriched_id', sa.String(length=36), nullable=True),
    sa.Column('subscriber_msisdn', sa.String(length=32), nullable=True),
    sa.Column('service_type', sa.String(length=16), nullable=True),
    sa.Column('call_direction', sa.String(length=16), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('selected_base_rule_id', sa.String(length=36), nullable=True),
    sa.Column('selected_rule_ids', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('expected_charge', sa.Numeric(precision=18, scale=6), server_default='0', nullable=False),
    sa.Column('actual_charge', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('variance_amount', sa.Numeric(precision=18, scale=6), server_default='0', nullable=False),
    sa.Column('absolute_variance', sa.Numeric(precision=18, scale=6), server_default='0', nullable=False),
    sa.Column('variance_percentage', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('rating_status', sa.String(length=24), nullable=False),
    sa.Column('enrichment_status', sa.String(length=32), nullable=True),
    sa.Column('actual_charge_status', sa.String(length=32), nullable=True),
    sa.Column('explanation', sa.Text(), server_default='', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('rating_result_id', name=op.f('pk_rating_result_final')),
    sa.UniqueConstraint('usage_id', 'charge_component', name='uq_rating_result_final_usage_id')
    )
    op.create_index(op.f('ix_rating_result_final_rating_status'), 'rating_result_final', ['rating_status'], unique=False)
    op.create_index('ix_rating_result_final_run', 'rating_result_final', ['run_id'], unique=False)
    op.create_index('ix_rating_result_final_status', 'rating_result_final', ['rating_status', 'event_date'], unique=False)
    op.create_index('ix_rating_result_final_subscriber', 'rating_result_final', ['subscriber_msisdn'], unique=False)
    op.create_index('ix_rating_result_final_variance', 'rating_result_final', ['absolute_variance'], unique=False)
    op.create_table('rating_usage_exception',
    sa.Column('exception_id', sa.String(length=36), nullable=False),
    sa.Column('usage_id', sa.String(length=128), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=True),
    sa.Column('exception_type', sa.String(length=32), nullable=False),
    sa.Column('exception_code', sa.String(length=48), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('status', sa.String(length=16), server_default='OPEN', nullable=False),
    sa.Column('retry_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('exception_id', name=op.f('pk_rating_usage_exception')),
    sa.UniqueConstraint('usage_id', 'exception_type', name='uq_rating_usage_exception_usage_id')
    )
    op.create_index('ix_rating_usage_exception_run', 'rating_usage_exception', ['run_id'], unique=False)
    op.create_index('ix_rating_usage_exception_status', 'rating_usage_exception', ['status', 'exception_code'], unique=False)
    op.create_table('rule_evaluation_audit',
    sa.Column('evaluation_id', sa.String(length=36), nullable=False),
    sa.Column('usage_id', sa.String(length=128), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=True),
    sa.Column('rule_id', sa.String(length=36), nullable=False),
    sa.Column('rule_key', sa.String(length=80), nullable=True),
    sa.Column('rule_name', sa.String(length=255), nullable=True),
    sa.Column('rule_stage', sa.String(length=32), nullable=False),
    sa.Column('evaluation_status', sa.String(length=24), nullable=False),
    sa.Column('rejection_reason', sa.String(length=32), nullable=True),
    sa.Column('detail', sa.Text(), server_default='', nullable=False),
    sa.Column('priority', sa.Integer(), server_default='0', nullable=False),
    sa.Column('specificity_score', sa.Integer(), server_default='0', nullable=False),
    sa.Column('rule_version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('exclusive_group', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('evaluation_id', name=op.f('pk_rule_evaluation_audit')),
    sa.UniqueConstraint('usage_id', 'rule_id', name='uq_rule_evaluation_audit_usage_id')
    )
    op.create_index('ix_rule_evaluation_audit_rule_status', 'rule_evaluation_audit', ['rule_id', 'evaluation_status'], unique=False)
    op.create_index('ix_rule_evaluation_audit_run', 'rule_evaluation_audit', ['run_id'], unique=False)
    op.create_index('ix_rule_evaluation_audit_usage', 'rule_evaluation_audit', ['usage_id', 'rule_stage'], unique=False)
    op.create_table('subscriber_group_membership',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('msisdn', sa.String(length=32), nullable=False),
    sa.Column('subscriber_id', sa.String(length=64), nullable=True),
    sa.Column('group_code', sa.String(length=64), nullable=False),
    sa.Column('group_type', sa.String(length=32), server_default='SEGMENT', nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('source_system', sa.String(length=64), server_default='MANUAL', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscriber_group_membership')),
    sa.UniqueConstraint('msisdn', 'group_code', 'effective_from', name='uq_subscriber_group_membership_msisdn')
    )
    op.create_index('ix_subscriber_group_membership_lookup', 'subscriber_group_membership', ['msisdn', 'effective_from', 'effective_to'], unique=False)
    op.create_index(op.f('ix_subscriber_group_membership_msisdn'), 'subscriber_group_membership', ['msisdn'], unique=False)
    op.add_column('cdr_enriched', sa.Column('usage_id', sa.String(length=128), nullable=True))
    op.add_column('cdr_enriched', sa.Column('source_file', sa.String(length=512), nullable=True))
    op.add_column('cdr_enriched', sa.Column('source_record_number', sa.String(length=64), nullable=True))
    op.add_column('cdr_enriched', sa.Column('duplicate_hash', sa.String(length=64), nullable=True))
    op.add_column('cdr_enriched', sa.Column('call_direction', sa.String(length=16), nullable=True))
    op.add_column('cdr_enriched', sa.Column('event_end_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('cdr_enriched', sa.Column('charged_party', sa.String(length=32), nullable=True))
    op.add_column('cdr_enriched', sa.Column('cell_id', sa.String(length=32), nullable=True))
    op.add_column('cdr_enriched', sa.Column('location_area_code', sa.String(length=32), nullable=True))
    op.add_column('cdr_enriched', sa.Column('call_reference', sa.String(length=64), nullable=True))
    op.add_column('cdr_enriched', sa.Column('serving_network', sa.String(length=16), nullable=True))
    op.add_column('cdr_enriched', sa.Column('subscriber_type', sa.String(length=16), nullable=True))
    op.add_column('cdr_enriched', sa.Column('customer_segment', sa.String(length=64), nullable=True))
    op.add_column('cdr_enriched', sa.Column('subscriber_groups', postgresql.ARRAY(sa.String(length=64)), server_default='{}', nullable=False))
    op.add_column('cdr_enriched', sa.Column('network_relation', sa.String(length=24), nullable=True))
    op.add_column('cdr_enriched', sa.Column('destination_type', sa.String(length=32), nullable=True))
    op.add_column('cdr_enriched', sa.Column('day_type', sa.String(length=16), nullable=True))
    op.add_column('cdr_enriched', sa.Column('bundle_ids', postgresql.ARRAY(sa.String(length=64)), server_default='{}', nullable=False))
    op.add_column('cdr_enriched', sa.Column('offer_ids', postgresql.ARRAY(sa.String(length=64)), server_default='{}', nullable=False))
    op.add_column('cdr_enriched', sa.Column('enrichment_status', sa.String(length=32), server_default='ENRICHED', nullable=False))
    op.add_column('cdr_enriched', sa.Column('enrichment_error', sa.Text(), nullable=True))
    op.add_column('cdr_enriched', sa.Column('processing_status', sa.String(length=16), server_default='PENDING', nullable=False))
    op.add_column('cdr_enriched', sa.Column('source_attributes', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.create_index(op.f('ix_cdr_enriched_call_reference'), 'cdr_enriched', ['call_reference'], unique=False)
    op.create_index('ix_cdr_enriched_duplicate_hash', 'cdr_enriched', ['duplicate_hash'], unique=False)
    op.create_index('ix_cdr_enriched_processing', 'cdr_enriched', ['processing_status', 'event_date'], unique=False)
    op.create_unique_constraint('uq_cdr_enriched_usage_id', 'cdr_enriched', ['usage_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_cdr_enriched_usage_id', 'cdr_enriched', type_='unique')
    op.drop_index('ix_cdr_enriched_processing', table_name='cdr_enriched')
    op.drop_index('ix_cdr_enriched_duplicate_hash', table_name='cdr_enriched')
    op.drop_index(op.f('ix_cdr_enriched_call_reference'), table_name='cdr_enriched')
    op.drop_column('cdr_enriched', 'source_attributes')
    op.drop_column('cdr_enriched', 'processing_status')
    op.drop_column('cdr_enriched', 'enrichment_error')
    op.drop_column('cdr_enriched', 'enrichment_status')
    op.drop_column('cdr_enriched', 'offer_ids')
    op.drop_column('cdr_enriched', 'bundle_ids')
    op.drop_column('cdr_enriched', 'day_type')
    op.drop_column('cdr_enriched', 'destination_type')
    op.drop_column('cdr_enriched', 'network_relation')
    op.drop_column('cdr_enriched', 'subscriber_groups')
    op.drop_column('cdr_enriched', 'customer_segment')
    op.drop_column('cdr_enriched', 'subscriber_type')
    op.drop_column('cdr_enriched', 'serving_network')
    op.drop_column('cdr_enriched', 'call_reference')
    op.drop_column('cdr_enriched', 'location_area_code')
    op.drop_column('cdr_enriched', 'cell_id')
    op.drop_column('cdr_enriched', 'charged_party')
    op.drop_column('cdr_enriched', 'event_end_time')
    op.drop_column('cdr_enriched', 'call_direction')
    op.drop_column('cdr_enriched', 'duplicate_hash')
    op.drop_column('cdr_enriched', 'source_record_number')
    op.drop_column('cdr_enriched', 'source_file')
    op.drop_column('cdr_enriched', 'usage_id')
    op.drop_index(op.f('ix_subscriber_group_membership_msisdn'), table_name='subscriber_group_membership')
    op.drop_index('ix_subscriber_group_membership_lookup', table_name='subscriber_group_membership')
    op.drop_table('subscriber_group_membership')
    op.drop_index('ix_rule_evaluation_audit_usage', table_name='rule_evaluation_audit')
    op.drop_index('ix_rule_evaluation_audit_run', table_name='rule_evaluation_audit')
    op.drop_index('ix_rule_evaluation_audit_rule_status', table_name='rule_evaluation_audit')
    op.drop_table('rule_evaluation_audit')
    op.drop_index('ix_rating_usage_exception_status', table_name='rating_usage_exception')
    op.drop_index('ix_rating_usage_exception_run', table_name='rating_usage_exception')
    op.drop_table('rating_usage_exception')
    op.drop_index('ix_rating_result_final_variance', table_name='rating_result_final')
    op.drop_index('ix_rating_result_final_subscriber', table_name='rating_result_final')
    op.drop_index('ix_rating_result_final_status', table_name='rating_result_final')
    op.drop_index('ix_rating_result_final_run', table_name='rating_result_final')
    op.drop_index(op.f('ix_rating_result_final_rating_status'), table_name='rating_result_final')
    op.drop_table('rating_result_final')
    op.drop_table('msc_ingest_cursor')
    op.drop_index('ix_holiday_calendar_date', table_name='holiday_calendar')
    op.drop_table('holiday_calendar')
    op.drop_index('ix_calculation_component_usage', table_name='calculation_component')
    op.drop_index('ix_calculation_component_type', table_name='calculation_component')
    op.drop_index('ix_calculation_component_run', table_name='calculation_component')
    op.drop_table('calculation_component')
    # ### end Alembic commands ###
